name: 'test'
on: [pull_request]

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout Repository'
        uses: actions/checkout@v3
      - name: 'ls'
        run: ls -al
      - name: 'cat'
        run: cat .nosana-ci.yml
      - name: 'echo'
        run: echo test2
